### ISSUE TITLE
"Rustacean" po polsku?

### ISSUE THREAD

**Issue by paytchoo** [paytchoo/book-pl#3]
Jak w temacie. "Rustowicz"?

**Comment by mati865** [comment]
Nie jestem lingwistą ale chyba `Rustowiec`, `Rustowcy` brzmi lepiej.

**Comment by paytchoo** [comment]
Faktycznie, brzmi dużo lepiej. Skoryguję u siebie. Jeśli nie będzie innych propozycji, to zamknę temat.
