### ISSUE TITLE
"Crate" w tłumaczeniu

### ISSUE THREAD

**Issue by katecpp** [paytchoo/book-pl#5]
Tłumaczycie "crate" czy zostawiacie po angielsku?
Jeśli po polsku to jak - "paczka"?

**Comment by kiug** [comment]
Skrzynia

czw., 15 mar 2018, 19:43 użytkownik katecpp <notifications@github.com>
napisał:

**Comment by paytchoo** [comment]
Problem w tym, że w niektórych miejscach słowa "crate" i "package" pojawiają się w tym samym zdaniu. "Skrzynia", póki co, pasuje w kontekście.

**Comment by katecpp** [comment]
W takim razie zostamy przy "skrzyni". Zamykam issue.
